package me.yhamarsheh.dbms.phase3.dbmsphase3.enums;

public enum SampleType {

    BLOOD,
    URINE,
    PLASMA,
    SERUM,
    TESTOSTERONE,
    DNA_ANALYSIS,
    VIRAL_DETECTION,
    RESPIRATORY_INFECTION,
    SWAB,
    AMNIOTIC_FLUID,
    SEMEN,
    BONE_MARROW,
    SWEAT,
    CREATINE_PHOSPHOKINASE,
    THYROID_IMMUNITY,
    RETINAL_BLOOD_CELLS,
    PITUITARY_GLAND,
    INSULIN_RESISTANCE,
    POLYCYSTIC_OVARY_SYNDROME,
    HEREDITARY_RECURRENT_MISCARRIAGE,
    IMMUNOLOGICAL_RECURRENT_MISCARRIAGE,
    DIGITAL_BRUCELLOSIS,
    ACCELERATED_HEARTBEAT;
}

// NORMALIZATION - TABLE FOR PRICES AND ADDING SAMPLE TYPES